global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'activemq-exporter'
    static_configs:
      - targets: ['app:8000']
        labels:
          service: 'activemq-metrics'
